### PR TITLE
Test skeleton and linting repo setup

### PR DESCRIPTION
**Pull request by m6jones**
Has the changes from https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/3

### CODE REVIEW

**Comment by ctwomey1** [comment]
Do we expect the sdk to be only polymer?  If we're generating just an esmodule sdk type thing we can perhaps do some unit tests against the raw classes, then reserve polymer testing for an integration suite?

**Comment by m6jones** [comment]
This is going to be primary an ES6 suite. However, it will have mixins related to polymer. It could also have support for other frameworks to make it easier to use.

Here are my thoughts about this that have been rattling inside my mind after I put up the PR:
- Testing needs to test browser support since this code will be used on all browsers.
- It be really nice to not require polymer testing for the es6 modules
- Have polymer/(other framework) testing in their own test folders

Honestly, my familiarity and experience with testing framework is not great. So to get to that point I require to do some reading and learning. This does meet the main point of testing on all browsers. At the same time, I really like doing what is correct.

I am on the fence on whether to close this and just wait till I do the required learning. Anyways, that is my current thoughts.

**Comment by ctwomey1** [comment]
I think you're on the right track,  I don't think it's necessary to close this pr. These are all good jump off points for testing the polymer mixin, and later a lit mixin.  

We just may want an additional suite eventually that tests things more granular as standalone modules.

**Comment by m6jones** [comment]
Sounds like a plan.

**Pull request merged**
