### PR TITLE
Add PR reminder checklist

### PR DESCRIPTION
**Pull request by mostlyfabulous**
### Based off the Team USA PR checklist from the LMS repo

Feedback welcomed! Not sure if we should keep this as an opt-in and add some `if` logic to only target interested parties

**Current reminders:**

- Semver keywords in commit message

- Rally US URL if applicable

### CODE REVIEW

**Comment by ronan-f** [comment]
I think this is a good addition as I keep forgetting the semantic release commit messages. I know a few teams maintain this repo so would like to hear input from others.

**Comment by wongvincent** [comment]
I think this is a good addition as I keep forgetting the semantic release commit messages. I know a few teams maintain this repo so would like to hear input from others.

**Review by pureooze — APPROVED** [review]
:shipit:

**Review by m6jones — APPROVED** [review]
This check list specially the semver one is really cool! I am looking forward to this and may steal it for other repos.

**Comment by pureooze** [comment]
Keep in mind there are also PR templates which you can use to do this kind of stuff if you want it to show up for all PRs. We used actions in the lms repo to avoid it being included for every single PR because it was a team specific checklist.

**Comment by pureooze** [comment]
Thought about this more, might actually be best left as an action, that will allow it to show up on dependabot PRs for reviewers. I dont know how dependabot deals with templates 🤔

**Comment by mostlyfabulous** [comment]
That's true, dependabot might break if there's a PR template conflicting with the PR description it generates.

Also, I wanted to keep this as an action so people can opt out of it if they want 😄

**Comment by mostlyfabulous** [comment]
@ronan-f Oh the irony I forgot to use semver here lol.

**Pull request merged**
