### PR TITLE
Egao/alerts tests

### PR DESCRIPTION
**Pull request by edwardg8**

### CODE REVIEW

**Comment by edwardg8** [comment]
I'm not sure why so many test failed, maybe related to `window.D2L.Siren.WhitelistBehavior._testMode`?

**Comment by m6jones** [comment]
It looks like it? Whitelist is breaking all the demos too.

**Comment by ctwomey1** [comment]
The tests are fixed in master, just make sure you merge that in

**Comment by edwardg8** [comment]
Awesome, thanks!!

**Pull request merged**
