### PR TITLE
US140575: Fix dirty check

### PR DESCRIPTION
**Pull request by martinwang-d2l**
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F641400889073%2Ftasks

Fix dirty check

### CODE REVIEW

**Review by mostlyfabulous — APPROVED** [review]
Please merge and squash this PR.

**Comment by mostlyfabulous** [comment]
image
@martinwang-d2l

**Comment by mostlyfabulous** [comment]
When you merge and squash, keep a semver keyword.

**Comment by mostlyfabulous** [comment]
What happened?
image

**Comment by martinwang-d2l** [comment]
Hmm, those were from the PR I put up this morning - those commits seem to have been duplicated when I put up my current PR, so when I merged and squashed, the duplicates got squashed but those three remained

**Comment by mostlyfabulous** [comment]
Ah, I didn't see the timestamps. Do you know why those commits have been duplicated?

**Comment by martinwang-d2l** [comment]
I think it might be to do with my branch - I continued work on my local branch, and pushed to the remote branch again for the PR. Didn't seem to have this issue before though ...

**Comment by mostlyfabulous** [comment]
So you merged PR1, then you stayed on the same branch for PR1, changed the name of the branch you were going to push to remote, added a commit for PR2 and then opened PR2?

**Pull request merged**
